### ISSUE TITLE
Integrating bio.tools

### ISSUE THREAD

**Issue by cfusterbarcelo** [bioimage-io/bioimageio-chatbot#1]
Integrating bio.tools in the chatbot

@matuskalas @wllei

**Comment by oeway** [comment]
We have now integrated bio.tools into the chatbot, see [here](https://github.com/bioimage-io/bioimageio-chatbot/blob/92be1b0bb1b8702c30f9f7c9c401ec0dc92bd4a1/knowledge-base-manifest.yaml#L19-L25).

cc @matuskalas
