### ISSUE TITLE
How to use the Code Interpreter in conjunction with prompts?

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#111]
The Bridget (BioImage Analyst) mode has a nifty Code Interpreter pane. But no guidance on how to use it. I tried `help()` but it gives a stack trace with `OSError: [Errno 29 I/O error`.

**Comment by oeway** [comment]
The current code interpreter pane is only used for debugging purpose, e.g. we can use it to inspect global variables produced by the chatbot code execution.

I have updated the welcome message in this PR: https://github.com/bioimage-io/bioimage.io/pull/394

Feel free to reopen!

**Comment by ctrueden** [comment]
Thanks. I opened a separate issue #128 for the `OSError` from `help()`.
