### ISSUE TITLE
Preserve chat history?

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#114]
It would be nice if, when switching to a different assistant type, the switch happened without reloading the page and losing previous chat history. My use case: I wanted to follow up on some information that Nina told me, by using Bridget to execute some code, but when I clicked on Bridget in the dropdown the page refreshed without warning and I lost the previous responses.

More generally: if the chatbot could remember previous conversations like ChatGPT does, that would be very helpful.

**Comment by oeway** [comment]
We discussed this, maybe the easiest way forward is to implement the capability to @ an assistant in a conversation.
