### ISSUE TITLE
Chatbot sometimes redundantly reloads data

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#119]
I told the chatbot to load a small PNG image, stripping the alpha channel, which worked: it did so then displayed it.

I then told the chatbot to perform a rolling ball background subtraction at radius 50. I noticed in the script it generated, as the output flew by, that it was calling `imread` again on the same file. Does it not have the dataset already loaded into a local variable, which can be reused?

I was able to avoid this behavior by appending "Save the result into a variable that can be subsequently reused" to my prompt—after doing so, the next prompt to perform the rolling ball successfully reused the already-loaded image (although the rolling ball operation ultimately failed—but that is a separate issue).

**Comment by oeway** [comment]
Thanks! While there is no straightforward way to control this behavior, I do adapted your prompt in the code here: https://github.com/bioimage-io/bioimage.io/pull/393

Feel free to reopen if this is still an obvious issue.
