### ISSUE TITLE
Is Firefox really unsupported for the Code Interpreter?

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#126]
When accessing the chatbot in Firefox, there is a warning header, which reads:

>  Warning! The code interpreter is only supported in Chromium based browsers (e.g. Chrome, Edge, Brave, etc.), please use a Chromium based browser to use the code interpreter. 

But I tried the Code Interpreter anyway and it appears to work just fine. Is there some subset of functionality which is broken? Or perhaps Firefox has improved enough now that it works, and this warning can be adjusted?

**Comment by oeway** [comment]
Yes, the folder mounting is not working since we used chrome-exclusive api at the moment. I have now improved the message: https://github.com/bioimage-io/bioimage.io/commit/06cdac3205027cbbc3d97769ce1335798d2538a9

**Comment by ctrueden** [comment]
The new message looks great. I'll close this issue, since I think the new message is clear and correct.
